name: Reproducible Build

on:
  push:
    branches:
      - "master"
    tags:
      - "*-rc"
  pull_request:
    types: [opened]
    branches:
      - "master"

# Declare default permissions as read only.
permissions: read-all

jobs:
  reproducible-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup Java & Gradle
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Verify files
        run: |
          gpg --keyserver https://secchannel.rsk.co/SUPPORT.asc --recv-keys 1DC9157991323D23FD37BAA7A6DBEAC640C5A14B
          gpg --verify --output SHA256SUMS SHA256SUMS.asc
          sha256sum --check SHA256SUMS

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
        name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        with:
          path: |
            gradle/wrapper/gradle-wrapper.jar
          key: gradle-wrapper-v1

      - name: Get Gradle wrapper
        if: steps.cache-gradle-wrapper.outputs.cache-hit != 'true'
        run: |
          ./configure.sh

      - name: Build
        run: |
          ./gradlew --no-daemon clean build -x test

      - name: Echo SHA256 checksums of JAR files
        run: |
          echo "SHA256 checksums of JAR files in rskj-core/build/libs/:"
          echo $(sha256sum rskj-core/build/libs/*.jar)

      - name: Archive build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: reproducible-build-files
          path: |
            rskj-core/build/libs/
            rskj-core/build/*.pom
